### ISSUE TITLE
Quiz 4 add cooking mode/ cooking instructions

### ISSUE THREAD

**Issue by bluebous** [CSBSJU-CS330-F21/ChefsKiss#55]
as a user I want to have a guided cooking instructions so that I can focus on cooking.

## tasks
- [ ] add option to start cooking mode
- [ ] add view for seeing step individually 
- [ ] add timers for timed steps

## done criteria
user is able to start cooking mode and be guided through each step of recipe.

@cameronbjork
